services:

  app:
    build: .
    ports:
      - "5000:5000"

    environment:
      MONGO_URI: mongodb://mongo:27017/

    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:7

    volumes:
      - mongo_data:/data/db

    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mongo_data: